/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MainRouteImport } from './app/_main'
import { Route as AuthRouteImport } from './app/_auth'
import { Route as MainIndexRouteImport } from './app/_main/index'
import { Route as MainSettingsRouteImport } from './app/_main/settings'
import { Route as MainNewRouteImport } from './app/_main/new'
import { Route as MainExploreRouteImport } from './app/_main/explore'
import { Route as MainUsernameRouteImport } from './app/_main/$username'
import { Route as AuthRegisterRouteImport } from './app/_auth/register'
import { Route as AuthLoginRouteImport } from './app/_auth/login'
import { Route as MainSettingsIndexRouteImport } from './app/_main/settings/index'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as MainSettingsAccountRouteImport } from './app/_main/settings/account'
import { Route as MainUsernameRepoRouteImport } from './app/_main/$username/$repo'
import { Route as MainUsernameRepoSettingsRouteImport } from './app/_main/$username/$repo/settings'
import { Route as MainUsernameRepoCommitsRouteImport } from './app/_main/$username/$repo/commits'
import { Route as MainUsernameRepoTreeSplatRouteImport } from './app/_main/$username/$repo/tree/$'
import { Route as MainUsernameRepoCommitsBranchRouteImport } from './app/_main/$username/$repo/commits/$branch'
import { Route as MainUsernameRepoBlobSplatRouteImport } from './app/_main/$username/$repo/blob/$'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainNewRoute = MainNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MainRoute,
} as any)
const MainExploreRoute = MainExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MainRoute,
} as any)
const MainUsernameRoute = MainUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MainRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSettingsAccountRoute = MainSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MainSettingsRoute,
} as any)
const MainUsernameRepoRoute = MainUsernameRepoRouteImport.update({
  id: '/$repo',
  path: '/$repo',
  getParentRoute: () => MainUsernameRoute,
} as any)
const MainUsernameRepoSettingsRoute =
  MainUsernameRepoSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoCommitsRoute = MainUsernameRepoCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => MainUsernameRepoRoute,
} as any)
const MainUsernameRepoTreeSplatRoute =
  MainUsernameRepoTreeSplatRouteImport.update({
    id: '/tree/$',
    path: '/tree/$',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)
const MainUsernameRepoCommitsBranchRoute =
  MainUsernameRepoCommitsBranchRouteImport.update({
    id: '/$branch',
    path: '/$branch',
    getParentRoute: () => MainUsernameRepoCommitsRoute,
  } as any)
const MainUsernameRepoBlobSplatRoute =
  MainUsernameRepoBlobSplatRouteImport.update({
    id: '/blob/$',
    path: '/blob/$',
    getParentRoute: () => MainUsernameRepoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/$username': typeof MainUsernameRouteWithChildren
  '/explore': typeof MainExploreRoute
  '/new': typeof MainNewRoute
  '/settings': typeof MainSettingsRouteWithChildren
  '/': typeof MainIndexRoute
  '/$username/$repo': typeof MainUsernameRepoRouteWithChildren
  '/settings/account': typeof MainSettingsAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/': typeof MainSettingsIndexRoute
  '/$username/$repo/commits': typeof MainUsernameRepoCommitsRouteWithChildren
  '/$username/$repo/settings': typeof MainUsernameRepoSettingsRoute
  '/$username/$repo/blob/$': typeof MainUsernameRepoBlobSplatRoute
  '/$username/$repo/commits/$branch': typeof MainUsernameRepoCommitsBranchRoute
  '/$username/$repo/tree/$': typeof MainUsernameRepoTreeSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/$username': typeof MainUsernameRouteWithChildren
  '/explore': typeof MainExploreRoute
  '/new': typeof MainNewRoute
  '/': typeof MainIndexRoute
  '/$username/$repo': typeof MainUsernameRepoRouteWithChildren
  '/settings/account': typeof MainSettingsAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings': typeof MainSettingsIndexRoute
  '/$username/$repo/commits': typeof MainUsernameRepoCommitsRouteWithChildren
  '/$username/$repo/settings': typeof MainUsernameRepoSettingsRoute
  '/$username/$repo/blob/$': typeof MainUsernameRepoBlobSplatRoute
  '/$username/$repo/commits/$branch': typeof MainUsernameRepoCommitsBranchRoute
  '/$username/$repo/tree/$': typeof MainUsernameRepoTreeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_main/$username': typeof MainUsernameRouteWithChildren
  '/_main/explore': typeof MainExploreRoute
  '/_main/new': typeof MainNewRoute
  '/_main/settings': typeof MainSettingsRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/$username/$repo': typeof MainUsernameRepoRouteWithChildren
  '/_main/settings/account': typeof MainSettingsAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
  '/_main/$username/$repo/commits': typeof MainUsernameRepoCommitsRouteWithChildren
  '/_main/$username/$repo/settings': typeof MainUsernameRepoSettingsRoute
  '/_main/$username/$repo/blob/$': typeof MainUsernameRepoBlobSplatRoute
  '/_main/$username/$repo/commits/$branch': typeof MainUsernameRepoCommitsBranchRoute
  '/_main/$username/$repo/tree/$': typeof MainUsernameRepoTreeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/$username'
    | '/explore'
    | '/new'
    | '/settings'
    | '/'
    | '/$username/$repo'
    | '/settings/account'
    | '/api/auth/$'
    | '/settings/'
    | '/$username/$repo/commits'
    | '/$username/$repo/settings'
    | '/$username/$repo/blob/$'
    | '/$username/$repo/commits/$branch'
    | '/$username/$repo/tree/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/$username'
    | '/explore'
    | '/new'
    | '/'
    | '/$username/$repo'
    | '/settings/account'
    | '/api/auth/$'
    | '/settings'
    | '/$username/$repo/commits'
    | '/$username/$repo/settings'
    | '/$username/$repo/blob/$'
    | '/$username/$repo/commits/$branch'
    | '/$username/$repo/tree/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/login'
    | '/_auth/register'
    | '/_main/$username'
    | '/_main/explore'
    | '/_main/new'
    | '/_main/settings'
    | '/_main/'
    | '/_main/$username/$repo'
    | '/_main/settings/account'
    | '/api/auth/$'
    | '/_main/settings/'
    | '/_main/$username/$repo/commits'
    | '/_main/$username/$repo/settings'
    | '/_main/$username/$repo/blob/$'
    | '/_main/$username/$repo/commits/$branch'
    | '/_main/$username/$repo/tree/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/new': {
      id: '/_main/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof MainNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/explore': {
      id: '/_main/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MainExploreRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$username': {
      id: '/_main/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof MainUsernameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/settings/account': {
      id: '/_main/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof MainSettingsAccountRouteImport
      parentRoute: typeof MainSettingsRoute
    }
    '/_main/$username/$repo': {
      id: '/_main/$username/$repo'
      path: '/$repo'
      fullPath: '/$username/$repo'
      preLoaderRoute: typeof MainUsernameRepoRouteImport
      parentRoute: typeof MainUsernameRoute
    }
    '/_main/$username/$repo/settings': {
      id: '/_main/$username/$repo/settings'
      path: '/settings'
      fullPath: '/$username/$repo/settings'
      preLoaderRoute: typeof MainUsernameRepoSettingsRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/commits': {
      id: '/_main/$username/$repo/commits'
      path: '/commits'
      fullPath: '/$username/$repo/commits'
      preLoaderRoute: typeof MainUsernameRepoCommitsRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/tree/$': {
      id: '/_main/$username/$repo/tree/$'
      path: '/tree/$'
      fullPath: '/$username/$repo/tree/$'
      preLoaderRoute: typeof MainUsernameRepoTreeSplatRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
    '/_main/$username/$repo/commits/$branch': {
      id: '/_main/$username/$repo/commits/$branch'
      path: '/$branch'
      fullPath: '/$username/$repo/commits/$branch'
      preLoaderRoute: typeof MainUsernameRepoCommitsBranchRouteImport
      parentRoute: typeof MainUsernameRepoCommitsRoute
    }
    '/_main/$username/$repo/blob/$': {
      id: '/_main/$username/$repo/blob/$'
      path: '/blob/$'
      fullPath: '/$username/$repo/blob/$'
      preLoaderRoute: typeof MainUsernameRepoBlobSplatRouteImport
      parentRoute: typeof MainUsernameRepoRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainUsernameRepoCommitsRouteChildren {
  MainUsernameRepoCommitsBranchRoute: typeof MainUsernameRepoCommitsBranchRoute
}

const MainUsernameRepoCommitsRouteChildren: MainUsernameRepoCommitsRouteChildren =
  {
    MainUsernameRepoCommitsBranchRoute: MainUsernameRepoCommitsBranchRoute,
  }

const MainUsernameRepoCommitsRouteWithChildren =
  MainUsernameRepoCommitsRoute._addFileChildren(
    MainUsernameRepoCommitsRouteChildren,
  )

interface MainUsernameRepoRouteChildren {
  MainUsernameRepoCommitsRoute: typeof MainUsernameRepoCommitsRouteWithChildren
  MainUsernameRepoSettingsRoute: typeof MainUsernameRepoSettingsRoute
  MainUsernameRepoBlobSplatRoute: typeof MainUsernameRepoBlobSplatRoute
  MainUsernameRepoTreeSplatRoute: typeof MainUsernameRepoTreeSplatRoute
}

const MainUsernameRepoRouteChildren: MainUsernameRepoRouteChildren = {
  MainUsernameRepoCommitsRoute: MainUsernameRepoCommitsRouteWithChildren,
  MainUsernameRepoSettingsRoute: MainUsernameRepoSettingsRoute,
  MainUsernameRepoBlobSplatRoute: MainUsernameRepoBlobSplatRoute,
  MainUsernameRepoTreeSplatRoute: MainUsernameRepoTreeSplatRoute,
}

const MainUsernameRepoRouteWithChildren =
  MainUsernameRepoRoute._addFileChildren(MainUsernameRepoRouteChildren)

interface MainUsernameRouteChildren {
  MainUsernameRepoRoute: typeof MainUsernameRepoRouteWithChildren
}

const MainUsernameRouteChildren: MainUsernameRouteChildren = {
  MainUsernameRepoRoute: MainUsernameRepoRouteWithChildren,
}

const MainUsernameRouteWithChildren = MainUsernameRoute._addFileChildren(
  MainUsernameRouteChildren,
)

interface MainSettingsRouteChildren {
  MainSettingsAccountRoute: typeof MainSettingsAccountRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
}

const MainSettingsRouteChildren: MainSettingsRouteChildren = {
  MainSettingsAccountRoute: MainSettingsAccountRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
}

const MainSettingsRouteWithChildren = MainSettingsRoute._addFileChildren(
  MainSettingsRouteChildren,
)

interface MainRouteChildren {
  MainUsernameRoute: typeof MainUsernameRouteWithChildren
  MainExploreRoute: typeof MainExploreRoute
  MainNewRoute: typeof MainNewRoute
  MainSettingsRoute: typeof MainSettingsRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainUsernameRoute: MainUsernameRouteWithChildren,
  MainExploreRoute: MainExploreRoute,
  MainNewRoute: MainNewRoute,
  MainSettingsRoute: MainSettingsRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
